// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Entities.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdGenero");

                    b.Property<string>("Imagen")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Core.Entities.Personaje", b =>
                {
                    b.Property<int>("IdPersonaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPersonaje");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Historia")
                        .HasColumnType("longtext");

                    b.Property<string>("Imagen")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(3,2)");

                    b.HasKey("IdPersonaje");

                    b.ToTable("Personajes");
                });

            modelBuilder.Entity("Core.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("longblob");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("longblob");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Core.Entities.VideoFilm", b =>
                {
                    b.Property<int>("IdVideoFilm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdVideoFilm");

                    b.Property<int>("Calificacion")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDeCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GeneroIdGenero")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdVideoFilm");

                    b.HasIndex("GeneroIdGenero");

                    b.ToTable("VideosFilm");
                });

            modelBuilder.Entity("PersonajeVideoFilm", b =>
                {
                    b.Property<int>("PersonajesAsociadosIdPersonaje")
                        .HasColumnType("int");

                    b.Property<int>("VideosFilmIdVideoFilm")
                        .HasColumnType("int");

                    b.HasKey("PersonajesAsociadosIdPersonaje", "VideosFilmIdVideoFilm");

                    b.HasIndex("VideosFilmIdVideoFilm");

                    b.ToTable("PersonajeVideoFilm");
                });

            modelBuilder.Entity("Core.Entities.VideoFilm", b =>
                {
                    b.HasOne("Core.Entities.Genero", null)
                        .WithMany("VideosFilm")
                        .HasForeignKey("GeneroIdGenero");
                });

            modelBuilder.Entity("PersonajeVideoFilm", b =>
                {
                    b.HasOne("Core.Entities.Personaje", null)
                        .WithMany()
                        .HasForeignKey("PersonajesAsociadosIdPersonaje")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.VideoFilm", null)
                        .WithMany()
                        .HasForeignKey("VideosFilmIdVideoFilm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Genero", b =>
                {
                    b.Navigation("VideosFilm");
                });
#pragma warning restore 612, 618
        }
    }
}
